In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [16]:
df = pd.read_csv('movies_metadata.csv')

C:\Users\ASUS\AppData\Local\Temp\ipykernel_15056\2089594497.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('movies_metadata.csv')

In [17]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [18]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [20]:
df.shape

(45466, 24)

In [21]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [22]:
df['poster_path']

0        /rhIRbceoE9lR4veEXuwCC2wARtG.jpg
1        /vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg
2        /6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg
3        /16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg
4        /e64sOI48hQXyru7naBFyssKFxVd.jpg
                       ...
45461    /jldsYflnId4tTWPx8es3uzsB1I8.jpg
45462    /xZkmxsNmYXJbKVsTRLLx3pqGHx7.jpg
45463    /d5bX92nDsISNhu3ZT69uHwmfCGw.jpg
45464    /aorBPO7ak8e8iJKT5OcqYxU3jlK.jpg
45465    /s5UkZt6NTsrS7ZF0Rh8nzupRlIU.jpg
Name: poster_path, Length: 45466, dtype: object

In [23]:
df = df.drop_duplicates().reset_index(drop=True)

In [24]:
df = df[['title', 'overview', 'genres', 'tagline', 'vote_average', 'popularity']]

In [25]:
df

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",NaN,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]",Just When His World Is Back To Normal... He's ...,5.7,8.387519
...,...,...,...,...,...,...
45448,Subdue,Rising and falling between a man and woman.,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",Rising and falling between a man and woman,4.0,0.072051
45449,Century of Birthing,An artist struggles to finish his work while a...,"[{'id': 18, 'name': 'Drama'}]",NaN,9.0,0.178241
45450,Betrayal,"When one of her hits goes wrong, a professiona...","[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",A deadly game of wits.,3.8,0.903007
45451,Satan Triumphant,"In a small town live two brothers, one a minis...",[],NaN,0.0,0.003503
45452,Queerama,50 years after decriminalisation of homosexual...,[],NaN,0.0,0.163015

In [26]:
df = df.dropna(subset=['title'])

In [27]:
df['overview'] = df['overview'].fillna('')

C:\Users\ASUS\AppData\Local\Temp\ipykernel_15056\279840550.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['overview'] = df['overview'].fillna('')

In [28]:
df.iloc[0]['genres']

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [50]:
import ast

df['genres'] = df['genres'].apply(lambda x: " ".join([i['name'] for i in ast.literal_eval(x)]))

C:\Users\ASUS\AppData\Local\Temp\ipykernel_15056\3544114650.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['genres'] = df['genres'].apply(lambda x: " ".join([i['name'] for i in ast.literal_eval(x)]))

In [52]:
df['tagline'] = df['tagline'].fillna('')

C:\Users\ASUS\AppData\Local\Temp\ipykernel_15056\733522008.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tagline'] = df['tagline'].fillna('')

In [53]:
df.isnull().sum()

title           0
overview        0
genres          0
tagline         0
vote_average    0
popularity      0
dtype: int64

In [55]:
df['tags'] = df['overview'] + " " + df['genres'] + " " + df['tagline']

C:\Users\ASUS\AppData\Local\Temp\ipykernel_15056\2481409169.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags'] = df['overview'] + " " + df['genres'] + " " + df['tagline']

In [57]:
df['tags'][0]

"Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences. Animation Comedy Family "

In [59]:
!pip install nltk

Collecting nltk
  Downloading nltk-3.9.4-py3-none-any.whl (1.6 MB)
                                              0.0/1.6 MB ? eta -:--:--
     --                                       0.1/1.6 MB 2.6 MB/s eta 0:00:01
     ---                                      0.1/1.6 MB 1.4 MB/s eta 0:00:01
     -----                                    0.2/1.6 MB 1.5 MB/s eta 0:00:01
     -------                                  0.3/1.6 MB 1.6 MB/s eta 0:00:01
     ---------                                0.4/1.6 MB 1.6 MB/s eta 0:00:01
     -----------                              0.5/1.6 MB 1.7 MB/s eta 0:00:01
     ------------                             0.5/1.6 MB 1.5 MB/s eta 0:00:01
     ---------------                          0.6/1.6 MB 1.7 MB/s eta 0:00:01
     ----------------                         0.7/1.6 MB 1.6 MB/s eta 0:00:01
     -------------------                      0.7/1.6 MB 1.6 MB/s eta 0:00:01
     ---------------------                    0.8/1.6 MB 1.7 MB/s eta 0:00:01
     ------------------------                 0.9/1.6 MB 1.7 MB/s eta 0:00:01
     -------------------------                1.0/1.6 MB 1.7 MB/s eta 0:00:01
     --------------------------               1.0/1.6 MB 1.7 MB/s eta 0:00:01
     -----------------------------            1.1/1.6 MB 1.7 MB/s eta 0:00:01
     -----------------------------            1.1/1.6 MB 1.7 MB/s eta 0:00:01
     -----------------------------            1.1/1.6 MB 1.7 MB/s eta 0:00:01
     -----------------------------            1.1/1.6 MB 1.7 MB/s eta 0:00:01
     -----------------------------------      1.4/1.6 MB 1.6 MB/s eta 0:00:01
     ------------------------------------     1.4/1.6 MB 1.6 MB/s eta 0:00:01
     --------------------------------------   1.5/1.6 MB 1.5 MB/s eta 0:00:01
     ---------------------------------------  1.5/1.6 MB 1.5 MB/s eta 0:00:01
     ---------------------------------------- 1.6/1.6 MB 1.5 MB/s eta 0:00:00
Requirement already satisfied: click in c:\users\asus\onedrive\desktop\jbooks\venv\lib\site-packages (from nltk) (8.3.2)
Requirement already satisfied: joblib in c:\users\asus\onedrive\desktop\jbooks\venv\lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\users\asus\onedrive\desktop\jbooks\venv\lib\site-packages (from nltk) (2026.1.15)
Requirement already satisfied: tqdm in c:\users\asus\onedrive\desktop\jbooks\venv\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\asus\onedrive\desktop\jbooks\venv\lib\site-packages (from click->nltk) (0.4.6)
Installing collected packages: nltk
Successfully installed nltk-3.9.4

[notice] A new release of pip is available: 23.1.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [62]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [63]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...

True

In [64]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [65]:
def preprocess_text(text):
    text = str(text).lower()
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    words = text.split()
    words = [word for word in words if word not in stop_words]
    words = [lemmatizer.lemmatize(word) for word in words]

    return " ".join(words)

In [66]:
df['tags'] = df['tags'].apply(preprocess_text)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_15056\743946967.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags'] = df['tags'].apply(preprocess_text)

In [67]:
df['tags'][1]

'sibling judy peter discover enchanted board game open door magical world unwittingly invite alan adult who trapped inside game year living room alans hope freedom finish game prof risky three find running giant rhinoceros evil monkey terrifying creature adventure fantasy family roll dice unleash excitement'

In [68]:
df = df.reset_index(drop=True)

In [97]:
# indices = pd.Series(df.index, index=df['title']).drop_duplicates()
indices = pd.Series(df.index, index=df['title'].str.lower()).drop_duplicates()
indices

title
toy story                          0
jumanji                            1
grumpier old men                   2
waiting to exhale                  3
father of the bride part ii        4
                               ...
subdue                         45442
century of birthing            45443
betrayal                       45444
satan triumphant               45445
queerama                       45446
Length: 45447, dtype: int64

In [98]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=50000, ngram_range=(1,2), stop_words='english')

In [99]:
tfidf_matrix = tfidf.fit_transform(df['tags'])

In [100]:
tfidf_matrix.shape

(45447, 50000)

In [101]:
from sklearn.metrics.pairwise import cosine_similarity

In [122]:
def recommend(title, n=10):
    title = title.lower()
    matches = df[df['title'].str.lower() == title]
    
    if matches.empty:
        matches = df[df['title'].str.lower().str.contains(title, na=False)]
    if matches.empty:
        return ['Movie not found']

    idx = matches.index[0]

    sim_score = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()
    similar_idx = sim_score.argsort()[::-1][1:n+1]

    return df['title'].iloc[similar_idx]

In [123]:
recommend('robots')

[0.05459503 0.02323853 0.00790277 ... 0.         0.         0.        ]

28972                                      Superstar Goofy
28065                                  Cody the Robosapien
43200                                  Spark: A Space Tail
30415                             Binta and the Great Idea
30170                                                 Mars
42891    Rainer Werner Fassbinder's World on a Wire: Lo...
28403                               France société anonyme
20372                                               Désiré
43983                                  Nightmare City 2035
45063                                        Tatu and Patu
Name: title, dtype: object

In [125]:
import pickle

pickle.dump(tfidf_matrix, open('tfidf_matrix.pkl', 'wb'))
pickle.dump(indices, open('indices.pkl', 'wb'))
df.to_pickle('df.pkl')
pickle.dump(tfidf, open('tfidf.pkl', 'wb'))